name: riverpod_provider

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  fluttertoast: ^8.2.10
  intl: ^0.20.1

flutter:
  uses-material-design: true
